[package]
name = "rust-url-shortener"
version = "0.1.0"
authors = ["Donald Whyte <donaldwhyte0@gmail.com>"]

[dependencies]
clap = "2.22.*"
iron = "0.5.*"
logger = "0.3.*"
persistent = "0.3.*"
r2d2 = "0.7.*"
r2d2_redis = "0.6.*"
redis = "0.8.*"
router = "*"
rustc-serialize = "*"
sha2 = "*"
